name: RETO_06_ROJO
channels:
  - defaults
dependencies:
  - asttokens=3.0.0=py312haa95532_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py312h540bb41_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.3=py312haa95532_0
  - contourpy=1.3.3=py312h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.16=py312h885b0b7_1
  - decorator=5.2.1=py312haa95532_0
  - executing=2.2.1=py312haa95532_0
  - expat=2.7.3=h9214b88_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py312h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=10.2.0=he2f9f60_1
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.31.0=py312h4442805_0
  - ipython=9.7.0=py312haa95532_0
  - ipython_pygments_lexers=1.1.1=py312haa95532_0
  - jedi=0.19.2=py312haa95532_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.6.3=py312haa95532_1
  - jupyter_core=5.8.1=py312haa95532_0
  - kiwisolver=1.4.8=py312h5da7b33_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libsodium=1.0.20=h83e8143_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.10.6=py312haa95532_1
  - matplotlib-base=3.10.6=py312h43afe63_1
  - matplotlib-inline=0.2.1=py312haa95532_0
  - missingno=0.5.2=py312haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py312h0b37514_0
  - mkl_fft=2.1.1=py312h300f80d_0
  - mkl_random=1.3.0=py312ha5e6156_0
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - nest-asyncio=1.6.0=py312haa95532_0
  - numexpr=2.14.1=py312h7660c64_0
  - numpy=2.3.5=py312h050da96_0
  - numpy-base=2.3.5=py312h1e017a8_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py312haa95532_1
  - pandas=2.3.3=py312h42c1672_1
  - parso=0.8.5=py312haa95532_0
  - pcre2=10.46=h5740b90_0
  - pillow=11.1.0=py312h096bfcc_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=py312haa95532_0
  - prompt-toolkit=3.0.52=py312haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py312h02ab6af_1
  - pure_eval=0.2.3=py312haa95532_0
  - pygments=2.19.2=py312haa95532_0
  - pyparsing=3.2.5=py312haa95532_0
  - pyqt=6.9.1=py312h12ec796_0
  - pyqt6-sip=13.10.2=py312h630b2a1_0
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py312haa95532_0
  - pywin32=311=py312h885b0b7_0
  - pyzmq=27.1.0=py312h7149c55_1
  - qtbase=6.9.2=hd965823_2
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - scipy=1.16.3=py312hbd6d557_0
  - seaborn=0.13.2=py312haa95532_3
  - setuptools=80.9.0=py312haa95532_0
  - sip=6.12.0=py312h706e071_0
  - six=1.17.0=py312haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py312haa95532_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py312h827c3e9_0
  - traitlets=5.14.3=py312haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py312haa95532_0
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\Markel\anaconda3\envs\RETO_06_ROJO
